//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulApiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uidt
    {
        public long id { get; set; }
        public string uid { get; set; }
        public string name { get; set; }
        public string href { get; set; }
        public string commentId { get; set; }
        public string nameWithType { get; set; }
        public string nameWithType_vb { get; set; }
        public string name_vb { get; set; }
        public string fullName { get; set; }
        public string fullName_vb { get; set; }
    }
}
